create table videos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  video_url text not null,
  is_complete boolean default false,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table videos enable row level security;

create policy "Individuals can create videos." on videos for
  insert with check (auth.uid() = user_id);
create policy "Individuals can view their own videos. " on videos for
  select using (auth.uid() = user_id);
create policy "Individuals can update their own videos." on videos for
  update using (auth.uid() = user_id);
create policy "Individuals can delete their own videos." on videos for
  delete using (auth.uid() = user_id);

create function public.handle_new_video()
returns trigger as $$
begin
  perform "net"."http_post"(
    'http://172.17.0.1:54321/get-transcription'::text,
    jsonb_build_object(
      'video', to_jsonb(new.*)
    ),
    headers:='{"Content-Type": "application/json"}'::jsonb
  ) as request_id;

  return new;
end;
$$ language plpgsql security definer;

create trigger on_video_created
  after insert on videos
  for each row execute procedure public.handle_new_video();
